# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Continuous Integration Tests

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * *'

jobs:
  preset-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preset: ["gcc-debug", "gcc-release"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25.x'
      - uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Run preset
        run: cmake --workflow --preset ${{ matrix.preset }}

  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        compiler:
          - cpp: g++
            c: gcc
          - cpp: clang++
            c: clang
        cpp_version: ["17", "20", "23", "26"]
        cmake_args:
          - description: "Default"
            args: ""
          - description: "TSan"
            args: "-DCMAKE_CXX_FLAGS=-fsanitize=thread"
          - description: "ASan"
            args: "-DCMAKE_CXX_FLAGS=-fsanitize=address -fsanitize=undefined"
        include:
          - platform: ubuntu-latest
            compiler:
              cpp: g++
              c: gcc
            cpp_version: "17"
            cmake_args:
              description: "Werror"
              cmake_args: "-DCMAKE_CXX_FLAGS='-Werror=all -Werror=extra'"

    name: "Bulid & Test: ${{ matrix.compiler.c }} ${{ matrix.cpp_version }} ${{ matrix.cmake_args.description }}"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
          ninjaVersion: "^1.11.1"
      - name: Print installed softwares
        run: |
          clang++ --version
          g++ --version
          cmake --version
          ninja --version
      - name: Build Release
        run: |
          cmake -B build -S . "-DCMAKE_CXX_STANDARD=${{ matrix.cpp_version }} ${{ matrix.cmake_args.args }}"
          cmake --build build --config Release --verbose
          cmake --build build --config Release --target all_verify_interface_header_sets
          cmake --install build --config Release --prefix /opt/beman.exemplar
          find /opt/beman.exemplar -type f
        env:
          CC: ${{ matrix.compiler.c }}
          CXX: ${{ matrix.compiler.cpp }}
          CMAKE_GENERATOR: "Ninja Multi-Config"
      - name: Test Release
        run: ctest --test-dir build --build-config Release
      - name: Build Debug
        run: |
          cmake -B build -S . "${{ matrix.cmake_args.args }}"
          cmake --build build --config Debug --verbose
          cmake --build build --config Debug --target all_verify_interface_header_sets
          cmake --install build --config Debug --prefix /opt/beman.exemplar
          find /opt/beman.exemplar -type f
        env:
          CC: ${{ matrix.compiler.c }}
          CXX: ${{ matrix.compiler.cpp }}
          CMAKE_GENERATOR: "Ninja Multi-Config"
      - name: Test Release
        run: ctest --test-dir build --build-config Debug

  create-issue-when-fault:
    runs-on: ubuntu-latest
    needs: [preset-test, test]
    if: failure() && github.event_name == 'schedule'
    steps:
      # See https://github.com/cli/cli/issues/5075
      - uses: actions/checkout@v4
      - name: Create issue
        run: |
          issue_num=$(gh issue list -s open -S "[SCHEDULED-BUILD] Build & Test failure" -L 1 --json number | jq 'if length == 0 then -1 else .[0].number end')

          body="**Build-and-Test Failure Report**
          - **Time of Failure**: $(date -u '+%B %d, %Y, %H:%M %Z')
          - **Commit**: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          - **Action Run**: [View logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          The scheduled build-and-test triggered by cron has failed.
          Please investigate the logs and recent changes associated with this commit or rerun the workflow if you believe this is an error."

          if [[ $issue_num -eq -1 ]]; then
            gh issue create --repo ${{ github.repository }} --title "[SCHEDULED-BUILD] Build & Test failure" --body "$body"
          else
            gh issue comment --repo ${{ github.repository }} $issue_num --body "$body"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
